Adjust Footer Design for Improved Aesthetics #43
Neel-07/Temperature-Converter pull request #67
Opened 2023-10-24 13:13 UTC by harshit1142

Added Hover effect on Social icons
Given the required padding and margin
Contact Us font size is reduced for small scene size

Demo: https://harshit1142.github.io/Temperature-Converter/

2023-10-24 13:50 UTC, Neel-07 requested changes
.social a {
  transition: box-shadow 0.3s ease-in-out; /* Add a smooth transition */
}

.social a:hover {
  box-shadow: 0 0 10px rgba(55, 191, 164, 0.7); /* Apply a shadow on hover */
}


can you modify and add these i think this  will make it look good.

2023-10-24 14:29 UTC, harshit1142 commented
Done

2023-10-25 04:19 UTC, Neel-07 approved these changes

2023-10-25 04:20 UTC, merged

2023-10-25 04:39 UTC, harshit1142 commented
Please Add hacktoberfest label is possible.